---
name: "TMDb Box Sets"
guid: "bc4aad2e-d3d0-4725-a5e2-fd07949e5b42"
version: "10"
targetAbi: "10.7.7.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Automatically create movie box sets based on TMDb collections"
description: "Automatically create movie box sets based on TMDb collections"
category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.TMDbBoxSets.dll"
changelog: |-
  - chore(deps): bump release-drafter/release-drafter from 5.15.0 to 5.17.6 (#59) @dependabot

  ### Code or Repo Maintenance ###
  - 10.8 support (#68) @crobibero

  ### CI & build changes ###
  - Use meta ci (#67) @crobibero
